$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: env-hoststar-autoscaler
image: d7a6feac73964dcba70d0a9ab016d8a8.azurecr.io/azureml/azureml_d28214de704a0e200df331e553a4f8c9
inference_config:
  liveness_route:
    port: 8080
    path: /health
  readiness_route:
    port: 8080
    path: /health
  scoring_route:
    port: 8080
    path: /score